---
title: "R Notebook"
---

```{r setup, include=TRUE}
library(tidyverse)
library(tidytuesdayR)
library(rvest)
library(magrittr)
library(scales)
library(extrafont)
library(ggforce)
library(glue)
library(jkmisc)
library(ggtext)
library(patchwork)
library(ggridges)
#library(ggtern)
#library(zoo)
#library(lubridate)
```

```{r read_data, include=TRUE}
tuesdata <- tidytuesdayR::tt_load(2020, week = 42)
datasaurus <- tuesdata$datasaurus
```

# EDA  

```{r glimpse_, include=TRUE}
datasaurus %>% 
  glimpse()
```

```{r summary_, include=TRUE}
split(datasaurus, datasaurus$dataset) %>% 
  cor(x=x,
      y=y,
      use = 'all.obs',
      method = 'pearson')
```

```{r my.theme, include=TRUE}
my.theme <- theme(
  plot.title = element_text(family="High Tower Text", color="black", face="bold", size=24, hjust=0), 
  plot.subtitle = element_text(family="High Tower Text", color="black", size=12, hjust=0), 
  axis.title = element_text(family="High Tower Text", color="black", face="bold", size=12), 
  axis.text = element_text(family="High Tower Text", color="black", size=9), 
  axis.ticks = element_blank(), 
  plot.caption = element_text(family="High Tower Text", color="black", size=12), 
  plot.background = element_blank(),
  panel.background =  element_blank(), 
  legend.background = element_blank(), 
  panel.grid.major = element_line(colour = "grey90", size = 0.5),
  panel.grid.minor = element_line(colour = "grey93", size = 0.5),
  panel.border = element_blank(), 
  #panel.border = element_rect(colour = "black", size = 0.5, fill=NA, linetype = 1),
  legend.title=element_blank(), 
  legend.text = element_text(family="High Tower Text", color="black", size=12, hjust=0),
  legend.position = 'top',
  strip.text = element_text(family="High Tower Text", color="black", size=14, face = 'bold'))
```

```{r sum_datasaurus, include=TRUE}
(sum_datasaurus <- datasaurus %>% 
  group_by(dataset) %>% 
  summarise_all(list(mean = mean, 
                     min = min, 
                     max = max,
                     sd = sd)))
```

```{r}
column_names <- c('dataset', 'Mean(x)', 'Mean(y)', 'Min(x)', 'Min(y)', 'Max(x)', 'Max(y)', 'Std Dev(x)', 'Std Dev(y)')

names(sum_datasaurus) <- column_names
```

```{r facet_datasaurus_viz, include=TRUE, fig.height=6.2, fig.width=3}
(facet_datasaurus_viz <- datasaurus %>% 
  filter(dataset %in% c('dino', 'bullseye', 'star')) %>% 
  ggplot(.) + 
  geom_point(aes(x=x,
                 y=y)) + 
  facet_wrap(~dataset,
             ncol = 1) + 
  my.theme)
```

```{r sum_datasaurus_2, include=TRUE}
(sum_datasaurus <- sum_datasaurus %>% 
  gather(summary_statistic, value, 2:9) %>% 
  mutate(value = round(value, 2)) %>% 
  mutate(label = paste(summary_statistic, value, sep = " = ")))

sum_datasaurus$summary_statistic <- factor(sum_datasaurus$summary_statistic, levels =  c('Std Dev(y)', 'Std Dev(x)', 
                                                                                         'Min(y)', 'Min(x)', 
                                                                                         'Max(y)', 'Max(x)', 
                                                                                         'Mean(y)', 'Mean(x)'))

sum_datasaurus
```


```{r datasaurus_summary_stat_viz, include=TRUE, fig.height=6.2, fig.width=3}
(datasaurus_summary_stat_viz <- sum_datasaurus %>% 
  filter(dataset %in% c('dino', 'bullseye', 'star')) %>% 
  mutate(nrow = row_number()) %>% 
  ggplot(.) + 
  geom_text(aes(x=1,
                y=-nrow,
                label=label),
            family="High Tower Text") + 
  facet_wrap(~dataset,
             ncol = 1) + 
  my.theme + 
  theme(panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        axis.title = element_blank(),
        axis.text = element_blank()))
```

```{r datasaurus_viz, include=TRUE, fig.height=6.5, fig.width=10}
(datasaurus_viz <- datasaurus_summary_stat_viz + facet_datasaurus_viz + 
  plot_annotation(theme = theme_jk(markdown=TRUE,
                                   plot_title_family = "High Tower Text",
                                   subtitle_family = "High Tower Text",
                                   caption_family = "High Tower Text",
                                   caption_size = 12),
                  title = '**Summary statistics can lie**',
                  subtitle = "Anscombe's Quartet is a statistical trap that demonstrates that summary statistics can be misleading. The visualization below shows three <br>**contemporary** examples of Anscombe's Quartet. Only by **visualizing** the data can you understand the dramatic differences in the distribution of the data.<br>As Alberto Cairo, a world famous information designer stated, '**Never trust summary statistics alone; always visualize your data**.'",
                  caption = 'Tidy Tuesday Week 41 (2020)'))
```

```{r save_graphics, include=TRUE}
ggsave("graphics/datasaurus_viz.png", datasaurus_viz,
       width = 10, height = 6.5, dpi = 300)
```