---
title: "R Notebook"
output: html_notebook
---

```{r setup, include=TRUE}
library(tidyverse)
library(tidytuesdayR)
library(rvest)
library(magrittr)
library(scales)
library(extrafont)
library(ggforce)
library(glue)
library(jkmisc)
library(ggtext)
library(patchwork)
#library(ggridges)
#library(ggtern)
library(tidytext)     #for text management
library(tidylo)
library(SnowballC)    #for text stemming
library(wordcloud)    #for word cloud
#library(zoo)
#library(lubridate)
```

```{r read_data, include=TRUE}
tuesdata <- tidytuesdayR::tt_load(2020, week = 40)
beyonce_lyrics <- tuesdata$beyonce_lyrics
taylor_swift_lyrics <- tuesdata$taylor_swift_lyrics
```

# EDA  

```{r glimpse_, include=TRUE}
beyonce_lyrics %>% 
  glimpse()
```

```{r tok_beyonce_lyrics, include=TRUE}
(tok_beyonce_lyrics <- beyonce_lyrics %>% 
   janitor::clean_names() %>% 
   tidytext::unnest_tokens(output = word, 
                          input = line) %>% 
   distinct(word, song_id, .keep_all = TRUE) %>% 
   select(word, artist_name))
```


```{r tok_taylor_swift_lyrics, include=TRUE}
(tok_taylor_swift_lyrics <- taylor_swift_lyrics %>% 
   janitor::clean_names() %>% 
   unnest_tokens(word, lyrics) %>% 
   distinct(word, artist, keep.all = TRUE) %>% 
   select(word, artist_name = artist))
```

```{r tidy_lyrics, include=TRUE}
(tidy_lyrics <- 
  bind_rows(tok_taylor_swift_lyrics, tok_beyonce_lyrics) %>% 
    anti_join(tidytext::get_stopwords(), by = 'word') %>% 
    count(artist_name, word, sort = TRUE) %>%
    filter(!is.na(word)))
```

```{r bind_log_odds, include=TRUE}
tidy_lyrics <- tidy_lyrics %>%
  bind_log_odds(artist_name, word, n)
```

```{r my.theme, include=TRUE}
my.theme <- theme(
  plot.title = element_text(family="Gabriola", color="black", face="bold", size=24, hjust=0), 
  plot.subtitle = element_text(family="Gabriola", color="black", size=12, hjust=0), 
  axis.title = element_text(family="Gabriola", color="gray98", face="bold", size=12), 
  axis.text = element_text(family="Gabriola", color="gray98", size=24), 
  axis.ticks = element_blank(), 
  plot.caption = element_text(family="Gabriola", color="black", size=12), 
  plot.background = element_rect(fill = "gray20", colour = NA),
  panel.background =  element_rect(fill = "gray20", colour = NA), 
  legend.background = element_rect(fill = "gray20", colour = NA), 
  panel.grid.major = element_blank(),
  panel.grid.minor = element_blank(),
  panel.border = element_blank(), 
  axis.text.y = element_blank(), 
  legend.title=element_blank(), 
  legend.text = element_text(family="Gabriola", color="black", size=12, hjust=0),
  legend.position = 'top',
  strip.text = element_text(family="Gabriola", color="black", size=14))
```

```{r}
(count_tswift <- taylor_swift_lyrics %>% 
  janitor::clean_names() %>% 
  unnest_tokens(word, lyrics) %>% 
  anti_join(get_stopwords(), by = 'word') %>% 
  janitor::tabyl(word) %>% 
  as.data.frame() %>% 
  arrange(-n))

(count_beyonce <- beyonce_lyrics %>% 
  janitor::clean_names() %>% 
  unnest_tokens(word, line) %>% 
  anti_join(get_stopwords(), by = 'word') %>% 
  janitor::tabyl(word) %>% 
  as.data.frame() %>% 
  arrange(-n))
```

```{r tswift_BoW_viz, include=TRUE, fig.height=6.2}
(tswift_BoW_viz <- count_tswift %>% 
  slice_max(percent, n=10) %>% 
  ggplot(.,
         aes(x=percent,
             y=reorder(word, percent))) + 
  geom_col(fill = 'cyan3') + 
  geom_text(aes(label = word),
            hjust = 1.5,
            size = 12,
            color = 'gray98',
            family = 'Gabriola',
            fontface = 'bold') + 
  labs(x='\nWord Count (% of corpus)',
       y='') + 
  scale_x_continuous(labels = percent) + 
  my.theme)
```

```{r beyonce_BoW_viz, include=TRUE, fig.height=6.2}
(beyonce_BoW_viz <- count_beyonce %>% 
  slice_max(percent, n=10) %>% 
  ggplot(.,
         aes(x=percent,
             y=reorder(word, percent))) + 
  geom_col(fill = 'green3') + 
  geom_text(aes(label = word),
            hjust = 1.5,
            size = 12,
            color = 'gray98',
            family = 'Gabriola',
            fontface = 'bold') + 
  labs(x='\nWord Count (% of corpus)',
       y='') + 
  scale_x_continuous(labels = percent) + 
  my.theme)
``` 

```{r fig.height=10}
(BoW_viz <- tswift_BoW_viz + beyonce_BoW_viz + 
  plot_annotation(title = glue('Most frequently used words in ',
                               {highlight_text("Taylor Swift", "cyan3", "b", size = 60)}, 
                               ' and ', 
                               {highlight_text("Beyonce", "green3", "b", size = 60)}, ' songs'),
                  subtitle = 'Top 10 songs by artist',
                  caption = '<br><b>Tidy Tuesday Week 40 (2020)',
                  theme = theme_jk(markdown = TRUE, 
                                   dark = TRUE,
                                   plot_title_family = "Gabriola", 
                                   subtitle_family = "Gabriola",
                                   subtitle_size = 40,
                                   caption_family = "Gabriola",
                                   caption_size = 30, 
                                   plot_title_size = 60)))
```

```{r save, include=TRUE}
ggsave("graphics/BoW_viz.png", BoW_viz,
       width = 18, height = 10, dpi = 300)
```
