---
title: "R Notebook"
output: html_notebook
---

```{r setup, include=TRUE}
library(tidyverse)
library(tidytuesdayR)
library(rvest)
library(magrittr)
library(scales)
library(extrafont)
library(ggforce)
library(glue)
library(jkmisc)
library(ggtext)
library(patchwork)
library(ggridges)
library(ggtern)
#library(zoo)
#library(lubridate)
```

```{r read_data, include=TRUE}
tuesdata <- tidytuesdayR::tt_load(2020, week = 3)
passwords <- tuesdata$passwords
```

# EDA  

```{r glimpse_, include=TRUE}
passwords %>% 
  glimpse()
```

```{r summary_, include=TRUE}
passwords %>% 
  summary()
```

```{r my.theme, include=TRUE}
my.theme <- theme(
  plot.title = element_text(family="Courier New", color="black", face="bold", size=24, hjust=0), 
  plot.subtitle = element_text(family="Courier New", color="black", size=12, hjust=0), 
  axis.title = element_text(family="Courier New", color="black", face="bold", size=12), 
  axis.text = element_text(family="Courier New", color="black", size=18), 
  axis.ticks.y = element_blank(), 
  plot.caption = element_text(family="Courier New", color="black", size=12), 
  plot.background = element_blank(),
  panel.background =  element_blank(), 
  legend.background = element_blank(), 
  panel.grid.major = element_line(colour = "grey90", size = 0.5),
  panel.grid.minor = element_line(colour = "grey93", size = 0.5),
  panel.border = element_blank(), 
  #panel.border = element_rect(colour = "black", size = 0.5, fill=NA, linetype = 1),
  legend.title=element_blank(), 
  legend.text = element_text(family="Courier New", color="black", size=12, hjust=0),
  legend.position = 'top',
  strip.text = element_text(family="Courier New", color="black", size=14))
```

```{r}
passwords %>% 
  slice_max(strength)
```


```{r strength_viz, include=TRUE, fig.height=6.2}
(strength_viz <- passwords %>% 
  filter(!is.na(category)) %>% 
  group_by(category) %>% 
  mutate(mean_password_strength = mean(strength),
         median_password_strength = median(strength)) %>% 
  ggplot(.,
         aes(x=strength,
                 y=reorder(category, 
                           median_password_strength))) + 
  geom_jitter(aes(color=category),
              height=.2, width = .5) + 
  geom_vline(aes(xintercept = median(strength)),
             linetype='dashed') + 
  ggrepel::geom_text_repel(data=. %>% 
                             ungroup() %>% 
                             slice_max(strength),
                            aes(label=password),
                           force=10,
                           family='Courier New',
                           size=6) + 
  labs(x='\nRelative strength of password',
       y='') + 
  my.theme + 
  #theme_minimal() + 
  theme(legend.position = 'none') + 
  plot_annotation(
    theme = theme_jk(markdown=TRUE,
                     plot_title_family = 'Courier New',
                     subtitle_family = 'Courier New',
                     caption_family = 'Courier New'),
    title = 'Relative **password strength** by category of password',
    subtitle = 'Each dot represents a unique password from the Knowledge is Beautiful password database<br>**rush2112** is the password with the highest strength score in the dataset',
    caption = 'Tidy Tuesday Week 3 (2020)<br>**Source**: Knowledge is Beautiful'))
```

```{r save_plot, include=TRUE}
ggsave("graphics/strength_viz.png", strength_viz,
       width = 10, height = 6.5, dpi = 300)
```