---
title: "R Notebook"
output: html_notebook
---

# Setup

```{r setup, include=TRUE}
library(tidyverse)
#library(tidytuesdayR)
#library(scales)
library(glue)
library(patchwork)
library(ggtext)
library(sysfonts)
library(showtext)
#library(gt)            #for great tables
library(camcorder)     #for recording viz evoluation & fixing canvas size
#library(gtExtras)      #for font awesome icons in gt tables
library(janitor)       #for clean_names()
library(hms)           #for as_hms()
#for special viz types
#library(ggbump)
#library(gghighlight)

#for irregular functions
#library(extrafont)
#library(htmltools)     #for tagList()
```

```{r fonts, include=TRUE}
# First argument = name in R
# Second argument = path to .otf-file
#font_add('fa-reg', 'fonts/Font Awesome 6 Free-Regular-400.otf')
font_add('fa-brands', 'fonts/Font Awesome 6 Brands-Regular-400.otf')
#font_add('fa-solid', 'fonts/Font Awesome 6 Free-Solid-900.otf')

sysfonts::font_add_google("Lato","lato")
showtext::showtext_auto()
showtext::showtext_opts(dpi=300)
```

```{r icons, include=TRUE}
txt <- 'black'
twitter <- glue("<span style='font-family:fa-brands; color:{txt}'>&#xf099;</span>")
github <- glue("<span style='font-family:fa-brands; color:{txt}'>&#xf09b;</span>")
#floppy <- glue("<span style='font-family:fa-solid; color:{txt}'>&#xf0c7;</span>")
space <- glue("<span style='color:black;font-size:1px'>'</span>")
```

```{r my.theme, include=TRUE}
my.theme <- theme(
  text = element_text(family = 'lato'), 
  plot.title = element_textbox_simple(color="black", face="bold", size=20, hjust=0), 
  plot.subtitle = element_textbox_simple(color="black", size=12, hjust=0), 
  axis.title = element_blank(), 
  axis.text = element_blank(), 
  axis.ticks = element_blank(),
  axis.line = element_blank(), 
  plot.caption = element_textbox_simple(color="black", size=12), 
  panel.background =  element_blank(), 
  panel.grid.major = element_blank(),
  panel.grid.minor = element_blank(),
  panel.border = element_blank(), 
  legend.title=element_blank(), 
  legend.text = element_text(color="black", size=12, hjust=0),
  legend.position = 'top',
  strip.text = element_text(color="black", size=14, face='bold'),
  strip.background = element_blank())
```

```{r read_data, include=TRUE}
df_myles <- read_csv('./data/huckleberry_myles2.csv') %>% 
  clean_names() %>% 
  mutate(name = as.factor('Myles'))

df_hazel <- read_csv('./data/huckleberry_hazel.csv') %>% 
  clean_names() %>% 
  mutate(name = as.factor('Hazel'))
```

```{r add_hms, include=TRUE}
df_myles <- df_myles %>% 
  mutate(date = lubridate::as_date(start),
         start_time = hms::as_hms(start),
         end_time = hms::as_hms(end),
         dob = lubridate::as_date('2019-04-12'),
         age = date - dob) %>% 
  select(date, name, type, start_time, end_time, age) %>% 
  arrange(date) %>% 
  filter(type == 'Sleep',
         age <= 30)

df_hazel <- df_hazel %>% 
  mutate(date = lubridate::as_date(start),
         start_time = hms::as_hms(start),
         end_time = hms::as_hms(end),
         dob = lubridate::as_date('2021-02-03'),
         age = date - dob) %>% 
  select(date, name, type, start_time, end_time, age) %>% 
  arrange(date) %>% 
  filter(type == 'Sleep',
         age <= 30)

df_combined <- bind_rows(df_myles, df_hazel)
```

# Viz

```{r start_camcorder, include=TRUE}
camcorder::gg_record(
  dir = 'img', dpi = 300, width = 16, height = 9, units = 'cm'
)
```

```{r viz_text, include=TRUE}
title_text <- 'Learning to sleep is hard work'

subtitle_text <- glue("<span style='color:cornflowerblue;font-face:bold'>Myles</span> and <span style='color:#9e9ac8;font-face:bold'>Hazel's</span> sleep patterns during their first month")

caption_text <- glue("Tidy Tuesday Week 1 (2023) #byoDATA<br>{twitter} @mickey_rafa • {github} mrafa3/tidy_tuesday<br>Source: Personal recordings from Huckleberry app")

alt_text <- 'Stylized circular plot showing the sleep times of our children, Hazel and Myles, during their first month. White space indicates wake time during the day.'
```

```{r viz, include=TRUE}
(plot_circular <- df_combined %>% 
  ggplot(.) + 
  geom_segment(aes(x=start_time,
                   xend=end_time,
                   y=age,
                   yend=age,
                   color=name)) + 
  facet_wrap(~name) + 
  coord_polar(clip = 'off') + 
  labs(alt = alt_text) + 
  scale_color_manual(values = c('Myles' = 'cornflowerblue',
                                'Hazel' = '#9e9ac8')) + 
  my.theme + 
  theme(legend.position = 'none',
        strip.text = element_blank()))
```

Experimenting with example by Albert Rapp...

```{r explainer_text, include=TRUE}
# Save text data in a tibble
tib_summary_text <- tibble(
  x = 0, 
  y = 0.15, 
  label = c("**How to read this (ch)art:** colored<br>segments represent times when<br><span style = 'color:cornflowerblue'>**Myles**</span> or <span style = 'color:#9e9ac8'>**Hazel**</span> slept during their<br>first month. Each circle represents<br>a single day, with inner circles<br>illustrating newborn days and outer<br>circles illustrating days near 30 days<br>since birth.<br><br>Data quality may have suffered due<br>to sleep quality."))

# Create text plot with geom_richtext() and theme_void()
(text_plot <- tib_summary_text %>% 
  ggplot() +
  geom_richtext(
    aes(x, y, label = label),
    size = 3.6,
    family = 'lato',
    hjust = 0,
    vjust = 0,
    label.colour = NA
  ) +
  coord_cartesian(xlim = c(0, 1), ylim = c(0, 2), clip = 'off') +
  # clip = 'off' is important for putting it together later.
  theme_void())
```


```{r add_patchwork, include=TRUE}
plot_circular_2 <- plot_circular + 
  text_plot + 
  plot_layout(widths = c(0.55, 0.45)) + 
  plot_annotation(
    title = title_text,
    subtitle = subtitle_text,
    caption = caption_text, 
    theme = theme(text = element_text(family = 'lato'),
                  plot.title = element_textbox_simple(color="black", 
                                                      face="bold", size=22, hjust=0), 
                  plot.subtitle = element_textbox_simple(color="black", size=14, hjust=0), 
                  plot.caption = element_textbox_simple(color="black", size=9), 
      plot.background = element_rect(fill = 'white', colour = NA)))
plot_circular_2
ggsave("./graphics/plot_circular_3.png", 
       width = 10, 
       height = 6.5,
       dpi = 300)
```


```{r save_plot, include=TRUE}
ggsave("./graphics/plot_circular_test.png", plot_circular_2,
       width = 10, height = 6.5, dpi = 300)
```

