---
title: "R Notebook"
output: html_notebook
---

```{r setup, include=TRUE}
library(tidyverse)
library(tidytuesdayR)
library(janitor)
library(rvest)
library(magrittr)
library(scales)
library(extrafont)
library(glue)
library(ggtext)
library(patchwork)
library(htmltools)
library(sysfonts)
library(showtext)
library(geomtextpath)
#library(ggridges)
#library(ggforce)
#library(ggtern)
#library(zoo)
#library(lubridate)
```

```{r font_add, include=TRUE}
# First argument = name in R
# Second argument = path to .otf-file
font_add('fa-reg', 'fonts/Font Awesome 6 Free-Regular-400.otf')
font_add('fa-brands', 'fonts/Font Awesome 6 Brands-Regular-400.otf')
font_add('fa-solid', 'fonts/Font Awesome 6 Free-Solid-900.otf')
```

```{r showtext, include=TRUE}
sysfonts::font_add_google("Ubuntu","ubuntu")
showtext::showtext_auto()
showtext::showtext_opts(dpi=300)
```

```{r read_data, include=TRUE}
tuesdata <- tidytuesdayR::tt_load(2021, week = 6)
hbcu_all <- tuesdata$hbcu_all %>% 
  clean_names()
```

# EDA  

```{r glimpse_, include=TRUE}
hbcu_all %>% 
  glimpse()
```

```{r summary_, include=TRUE}
hbcu_all %>% 
  summary()
```

```{r}
(hbcu_all <- hbcu_all %>% 
  select(year, Men=males, Women=females) %>% 
  gather(gender, annual_enrollment, 2:3))
```


```{r my.theme, include=TRUE}
my.theme <- theme(text = element_text(family='ubuntu'),
  plot.title = ggtext::element_textbox_simple(face="bold", color="#444444", size=24, margin=margin(b=5)),
  plot.subtitle = ggtext::element_textbox_simple(color="#444444", size=14, 
                                                       margin=margin(b=10)),
  plot.caption = ggtext::element_textbox_simple(color="#444444", size=12),
  axis.title = element_text(color="black", face="bold", size=12), 
  axis.text = element_text(color="black", size=18), 
  axis.ticks = element_blank(), 
  plot.background = element_rect(fill = 'white'),
  panel.background = element_blank(),
  panel.grid.major = element_blank(),
  panel.grid.minor = element_blank(),
  panel.border = element_blank(), 
  legend.title=element_blank(), 
  legend.text = element_text(color="black", size=12, hjust=0),
  legend.position = 'top',
  strip.text = element_text(color="black", size=14))
```

```{r viz_colors, include=TRUE}
viz_colors <- c("Women" = "#663399", "Men" = "#33CC66")
```


```{r viz_text, include=TRUE}
title <- tagList(span("**Women**", style='color:#663399;'), "enrolling in HBCUs at historic rates")

subtitle <- tagList(p("HBCU Enrollments by Gender: 1976 - 2015"))
  
caption <- paste0("<span style='font-family:ubuntu;'>**Source**: TidyTuesday week 6 (2021)</span><br>",
                "<span style='font-family:fa-brands;'>&#xf099;</span>",
                 "<span style='font-family:ubuntu;'>@mickey.rafa</span>",
                 "<span style='font-family:ubuntu;color:white;'>....</span>",
                 "<span style='font-family:fa-brands;'>&#xf09b;</span>",
                 "<span style='font-family:ubuntu;color:white;'>.</span>",
                 "<span style='font-family:ubuntu;'>mrafa</span>")
```

```{r viz, include=TRUE, fig.height=3}
(plot_enrollment <- hbcu_all %>% 
  ggplot(aes(x=year,
             y=annual_enrollment,
             label=gender,
             color=gender)) + 
  geomtextpath::geom_textline(linewidth=2, hjust=1, vjust=-.5, fontface="bold", size=8) + 
  labs(x='',
       y='',
       title=title,
       subtitle = subtitle,
       caption = caption) + 
  scale_color_manual(values = viz_colors) + 
  scale_y_continuous(labels = comma, position = 'right') + 
  my.theme + 
  theme(legend.position = 'none'))
```

```{r save_plot, include=TRUE}
ggsave("graphics/hbcu_enrollment_by_gender.png", plot_enrollment,
       width = 10, height = 6.5, dpi = 300)
```