---
title: "Tidy Tuesday: Week 36 (2020)"
output: html_notebook
---

```{r setup, include=TRUE}
library(tidyverse)
library(tidytuesdayR)
library(janitor)
library(rvest)
library(magrittr)
library(scales)
library(extrafont)
library(ggforce)
library(glue)
library(jkmisc)
library(ggtext)
library(patchwork)
library(countrycode)
library(gt)
#library(ggbeeswarm)
#library(geofacet)             #only includes US states at the moment but supports user-specified grids
#see here for someone's created Africa grid: https://github.com/malinfax/africa-grid1

#library(ggridges)
#library(ggtern)
#library(zoo)
#library(lubridate)
```

```{r my.theme, include=TRUE}
my.theme <- theme(
  plot.title = element_text(family="Gill Sans MT", color="black", face="bold", size=24, hjust=0), 
  plot.subtitle = element_text(family="Gill Sans MT", color="black", size=12, hjust=0), 
  axis.title = element_text(family="Gill Sans MT", color="black", face="bold", size=12), 
  axis.text = element_text(family="Gill Sans MT", color="black", size=18), 
  axis.ticks.y = element_blank(), 
  plot.caption = element_text(family="Gill Sans MT", color="black", size=12), 
  plot.background = element_blank(),
  panel.background =  element_blank(), 
  legend.background = element_blank(), 
  panel.grid.major = element_line(colour = "grey90", size = 0.5),
  panel.grid.minor = element_line(colour = "grey93", size = 0.5),
  panel.border = element_blank(), 
  #panel.border = element_rect(colour = "black", size = 0.5, fill=NA, linetype = 1),
  legend.title=element_blank(), 
  legend.text = element_text(family="Gill Sans MT", color="black", size=12, hjust=0),
  legend.position = 'top',
  strip.text = element_text(family="Gill Sans MT", color="black", size=14))
```

```{r read_data, include=TRUE}
tuesdata <- tidytuesdayR::tt_load(2020, week = 36)
yield <- tuesdata$key_crop_yields
yield_fertilizer <- tuesdata$cereal_crop_yield_vs_fertilizer_application
```

# Wrangling  

```{r}
yield %>% 
  janitor::clean_names() %>% 
  left_join(x=.,
            y=countrycode::codelist %>% 
              select(continent, iso3c, un.regionsub.name) %>% 
              filter(complete.cases(.)),
            by=c('code' = 'iso3c'))
```


```{r yield_mutate, include=TRUE}
(yield %<>% 
  janitor::clean_names() %>% 
  left_join(x=.,
            y=countrycode::codelist %>% 
              select(continent, iso3c, un.regionsub.name) %>% 
              filter(complete.cases(.)),
            by=c('code' = 'iso3c')) %>% 
  gather(crop, yield, 4:14) %>% 
  mutate(decade = as.factor(year - (year %% 10)),
         crop = str_to_title(str_remove(crop, "_tonnes_per_hectare"))))
```

```{r yield_fertilizer_mutate, include=TRUE}
(yield_fertilizer %<>% 
  clean_names() %>% 
  left_join(x=.,
            y=countrycode::codelist %>% 
              select(continent, iso3c) %>% 
              filter(complete.cases(.)),
            by=c('code' = 'iso3c')) %>% 
   mutate(decade = as.factor(year - (year %% 10))) %>% 
   rename(yield = cereal_yield_tonnes_per_hectare,
          nitrogen = nitrogen_fertilizer_use_kilograms_per_hectare))
```

# Experimenting with `gt::` for effective tables  

```{r staples, include=TRUE}
staples <- c('Wheat', 'Rice', 'Maize', 'Soybeans', 'Cassava')
```

```{r}
yield %>% 
  filter(continent == 'Africa') %>% 
  distinct(un.regionsub.name)
```

```{r sadc, include=TRUE}
sadc <- c('Angola', 'Botswana', 'Comoros', 
          'Democratic Republic of Congo', 'Swaziland', 
          'Lesotho', 'Madagascar', 'Malawi', 'Mauritius',
          'Mozambique', 'Namibia', 'Seychelles', 
          'South Africa', 'Tanzania', 'Zambia', 'Zimbabwe')
```

```{r yield_gt, include=TRUE}
yield_gt <- yield %>% 
  filter(year >= 2015,
         entity %in% sadc) %>% 
  select(-c(decade, continent, code, un.regionsub.name)) %>% 
  spread(year, yield) %>% 
  rename(country = entity) %>%
  filter(crop == 'Maize') %>% 
  select(-crop) %>% 
  gt(rowname_col = 'country') %>% 
  fmt_number(columns = 2:last_col(),
             decimals = 1) %>% 
  fmt_missing(columns = 2:last_col(),
              missing_text = '-') %>% 
  tab_header(title = md("**Maize Yields in the Southern African Development Community**"),
             subtitle = md("*in tons per hectare* between 2015 and 2018")) %>% 
  #To highlight results of a row
  #tab_style(style = 
   #           list(cell_text(color = "red", style = "italic")),
    #        locations = cells_body(columns = 2:last_col(),
     #                              rows = country == "Zambia"
    #)) %>% 
  data_color(
    columns = 2:last_col(),
    colors = 
      scales::col_numeric(
        paletteer::paletteer_d(
          palette = "ggsci::green_material") %>% 
          as.character(),
        domain = NULL)) %>% 
  tab_source_note(source_note = md("**Source**: Our World In Data<br>**Inspiration**: https://themockup.blog/posts/2020-09-04-10-table-rules-in-r/")) %>% 
  tab_options(
    heading.subtitle.font.size = 12,
    heading.align = "left",
    table.border.top.color = "black",
    column_labels.border.bottom.color = "black",
    column_labels.border.bottom.width= px(3))
```

```{r save_yield_gt, include=TRUE}
yield_gt %>% 
  gtsave(filename = 'yield_gt.png',
         path = './/graphics/yield_gt.png')
```

# Visualizations  

```{r fig.height=7}
yield_fertilizer %>% 
  filter(complete.cases(.)) %>% 
  ggplot(.,
         aes(x=nitrogen,
             y=yield,
             color=continent)) + 
  geom_point() + 
  geom_smooth(method = 'glm', se = FALSE) + 
  facet_wrap(~ decade) + 
  my.theme
```

```{r fig.height=7}
test <- yield %>% 
  filter(entity %in% c('Western Africa', 'Southern Africa',
                       'Northern Africa', 'Middle Africa', 
                       'Eastern Africa', 'Low Income Food Deficit Countries'),
         crop %in% staples) %>% 
  ggplot(.) + 
  geom_line(aes(x=year,
                y=yield,
                group=crop,
                color=crop)) + 
  facet_wrap(~ entity) + 
  my.theme + 
  theme(axis.title = element_text())
```

```{r}
test
```

# EDA  

```{r glimpse_yield, include=TRUE}
yield %>% 
  glimpse()
```

```{r summary_yield, include=TRUE}
yield %>% 
  summary()
```


```{r fig.height=6.2}
yield %>% 
  ggplot(.) + 
  geom_boxplot(aes(x=`Wheat (tonnes per hectare)`,
                  y=decade)) + 
  my.theme
```

```{r hist_, include=TRUE, fig.height=6.2}

```

