---
title: "R Notebook"
output: html_notebook
---

# Setup

```{r setup, include=TRUE}
library(tidyverse)
library(tidytuesdayR)
library(scales)
library(extrafont)
library(glue)
library(patchwork)
library(ggtext)
library(ggbump)
library(gghighlight)
library(sysfonts)
library(showtext)
library(gt)
library(camcorder)
library(gtExtras)      #for font awesome icons in gt tables
library(janitor)       #for clean_names()
library(htmltools)     #for tagList()
```

```{r font_add, include=TRUE}
# First argument = name in R
# Second argument = path to .otf-file
#font_add('fa-reg', 'fonts/Font Awesome 6 Free-Regular-400.otf')
font_add('fa-brands', 'fonts/Font Awesome 6 Brands-Regular-400.otf')
#font_add('fa-solid', 'fonts/Font Awesome 6 Free-Solid-900.otf')
```

```{r showtext, include=TRUE}
sysfonts::font_add_google("Lato","lato")
showtext::showtext_auto()
showtext::showtext_opts(dpi=300)
```

```{r my.theme, include=TRUE}
my.theme <- theme(
  text = element_text(family = 'lato'), 
  plot.title = element_textbox_simple(color="black", face="bold", size=20, hjust=0), 
  plot.subtitle = element_textbox_simple(color="black", size=12, hjust=0), 
  #axis.title = element_blank(), 
  #axis.text = element_blank(), 
  axis.ticks = element_blank(),
  #axis.line = element_blank(), 
  plot.caption = element_textbox_simple(color="black", size=12), 
  panel.background =  element_blank(), 
  panel.grid.major = element_blank(),
  panel.grid.minor = element_blank(),
  panel.border = element_blank(), 
  legend.title=element_blank(), 
  legend.text = element_text(color="black", size=12, hjust=0),
  legend.position = 'top',
  strip.text = element_text(color="black", size=14))
```

```{r read_data, include=TRUE}
tuesdata <- tidytuesdayR::tt_load(2022, week = 35)

df <- tuesdata$pell %>% 
  clean_names()
```

```{r df_summary, include=TRUE}
df %>% 
  summary()
```

# Colorado 

```{r}
(df_colorado <- df %>% 
  filter(state == 'CO') %>% 
  mutate(award_per_recipent = award / recipient))
```

```{r}
df_colorado %>% 
  ggplot(.,
         aes(x=recipient)) + 
  geom_histogram()

df_colorado_min <- df_colorado %>% 
  filter(recipient >= 10) %>% 
  group_by(year) %>% 
  slice_min(award_per_recipent) %>% 
  mutate(min_max_label = 'Min')

df_colorado_max <- df_colorado %>% 
  filter(recipient >= 10) %>% 
  group_by(year) %>% 
  slice_max(award_per_recipent) %>% 
  mutate(min_max_label = 'Max')

df_colorado_min_max <- bind_rows(df_colorado_min, df_colorado_max)
```


```{r start_camcorder, include=TRUE}
camcorder::gg_record(
  dir = 'img', dpi = 300, width = 16, height = 9, units = 'cm'
)
```


```{r}
twitter <- glue("<span style='font-family:fa-brands; color:{txt}'>&#xf099;</span>")
github <- glue("<span style='font-family:fa-brands; color:{txt}'>&#xf09b;</span>")
#floppy <- glue("<span style='font-family:fa-solid; color:{txt}'>&#xf0c7;</span>")
space <- glue("<span style='color:black;font-size:1px'>'</span>")


subtitle <- glue(
"Almost 60% (1252/2122) of Star Trek narratives<br>
across all formats occur between the years<br>
2351 and 2380 {spock}")
```

```{r}
viz_colors <- c('Max' = '#645A7B', 'Min' = '#6ED187')
```


```{r viz_text, include=TRUE}
txt <- 'black'
twitter <- glue("<span style='font-family:fa-brands; color:{txt}'>&#xf099</span")

title_text <- 'Pell Grant Award Value per Recipient'
subtitle_text <- glue("<span style='color:#6ED187'>Min</span> and <span style='color:#645A7B'>Max</span> values each year in Colorado")
caption_text <- glue("Tidy Tuesday Week 35 (2022)<br>{twitter} @mickey.rafa • {github} mrafa3/tidy_tuesday")

max_value <- df_colorado_min_max %>% 
  filter(year == 2010,
         min_max_label == 'Max') %>% 
  pull(award_per_recipent)
```


```{r}
(viz_pell_colorado <- df_colorado_min_max %>% 
  ggplot(.,
         aes(x=year,
             y=award_per_recipent,
             color=min_max_label)) + 
  geom_point() + 
  geom_line() + 
  ggforce::geom_mark_circle(aes(filter = year == 2010 & min_max_label == 'Max', 
                                label = name,
                                description = glue("Peak value of {round(max_value, 0)} in 2010")),
                            label.family = 'lato',
                            label.fontsize = c(8, 6)) + 
  labs(x='',
       y='',
       title = title_text,
       subtitle = subtitle_text,
       caption = caption_text) + 
  scale_y_continuous(labels = c('', '2,000', '4,000', '6,000', ''),
                     limits = c(0,8000)) + 
  scale_color_manual(values = viz_colors) + 
  my.theme + 
  theme(legend.position = 'none')) 
```

```{r save_plot, include=TRUE}
ggsave("graphics/viz_pell_colorado.png", viz_pell_colorado,
       width = 10, height = 6.5, dpi = 300)
```

# Which state has the highest pell award per student?  

```{r include=FALSE}
(df_tbl <- df %>% 
  slice_max(year) %>% 
  group_by(state) %>% 
  summarise(sum_award = sum(award, na.rm = TRUE),
            sum_recipients = sum(recipient, na.rm = TRUE)) %>% 
  ungroup() %>% 
  mutate(award_per_recipient = sum_award / sum_recipients) %>% 
  arrange(-award_per_recipient))
```

```{r tbl_viz, include=TRUE} 
(tbl_viz <- df_tbl %>% 
  arrange(-sum_award) %>% 
  gt() %>% 
  gt::cols_label(state = 'State',
                 sum_award = 'Total Pell $',
                 sum_recipients = 'Total Pell Recipients',
                 award_per_recipient = 'Avg Pell Award $') %>% 
  tab_header(title = md("**Pell Grant Awards in 2017**"),
             subtitle = md("Schools in **New Hampshire** and **Puero Rico** average the lowest and highest average awards respectively")) %>% 
  tab_source_note(source_note = "Data from Tidy Tuesday Week 35 (2022)") %>% 
  fmt_currency(columns = c(sum_award, award_per_recipient), 
               decimals = 0) %>% 
  fmt_number(columns = c(sum_recipients), 
               decimals = 0) %>% 
  gt_highlight_rows(
    rows = c(10,39), 
    fill = "lightgrey",
    bold_target_only = TRUE,
    target_col = state
    ) %>% 
  gt_hulk_col_numeric(award_per_recipient) %>% 
  tab_style(
    locations = cells_column_labels(columns = everything()),
    style = list(
      #thick border
      cell_borders(sides = "bottom", weight = px(3)),
      #make text bold
      cell_text(weight = "bold")
    )
  ) %>% 
  #apply different style to title
  tab_style(locations = cells_title(groups = "title"),
            style = list(
              cell_text(weight = "bold", size = 24)
            )) %>% 
  #data_color(columns = c(goals),
   #          colors = goals_palette) %>% 
  opt_all_caps() %>% 
  opt_table_font(
    font = list(
      google_font("Nunito Sans"),
      default_fonts()
    )
  ) %>% 
  tab_options(
    #remove border between column headers and title
    column_labels.border.top.width = px(3),
    column_labels.border.top.color = "transparent",
    #remove border around the table
    table.border.top.color = "transparent",
    table.border.bottom.color = "transparent",
    #adjust font sizes and alignment
    source_notes.font.size = 12,
    heading.align = "left"
  ))
```

```{r gtsave_1, include=TRUE}
tbl_viz %>% gtsave(filename = "graphics/tbl_pell_by_state_2017.png")
```

