---
title: "R Notebook"
output: html_notebook
---

```{r setup, include=TRUE}
library(tidyverse)
library(tidytuesdayR)
library(rvest)
library(magrittr)
library(scales)
library(extrafont)
library(ggforce)
library(glue)
library(jkmisc)
library(ggtext)
library(patchwork)
library(ggridges)
library(ggtern)
#library(zoo)
#library(lubridate)
```

```{r read_data, include=TRUE}
tuesdata <- tidytuesdayR::tt_load(2020, week = 31)
penguins <- tuesdata$penguins
penguins_raw <- tuesdata$penguins_raw
```

# EDA  

```{r glimpse_penguins, include=TRUE}
penguins %>% 
  glimpse()
```

```{r glimpse_penguins_raw, include=TRUE}
penguins_raw %>% 
  glimpse()
```

```{r expedition_attempts, include=TRUE}

```

```{r summary, include=TRUE}
```

```{r distinct_variable, include=TRUE}
```

```{r hist, include=TRUE, fig.height=6.2}
```


#   

```{r my.theme, include=TRUE}
my.theme <- theme(
  plot.title = element_text(family="Gill Sans MT", color="black", face="bold", size=24, hjust=0), 
  plot.subtitle = element_text(family="Gill Sans MT", color="black", size=12, hjust=0), 
  axis.title = element_text(family="Gill Sans MT", color="black", face="bold", size=12), 
  axis.text = element_text(family="Gill Sans MT", color="black", size=18), 
  axis.ticks.y = element_blank(), 
  plot.caption = element_text(family="Gill Sans MT", color="black", size=12), 
  plot.background = element_blank(),
  panel.background =  element_blank(), 
  legend.background = element_blank(), 
  panel.grid.major = element_line(colour = "grey90", size = 0.5),
  panel.grid.minor = element_line(colour = "grey93", size = 0.5),
  panel.border = element_blank(), 
  #panel.border = element_rect(colour = "black", size = 0.5, fill=NA, linetype = 1),
  legend.title=element_blank(), 
  legend.text = element_text(family="Gill Sans MT", color="black", size=12, hjust=0),
  legend.position = 'top',
  strip.text = element_text(family="Gill Sans MT", color="black", size=14))
```

```{r}
penguins %>% 
  summary()
```

```{r peng_cols, include=TRUE}
peng_cols <- c('Biscoe' = 'cornflowerblue', 
                 'Dream' = 'seagreen3',
                 'Torgersen' = 'maroon1',
                 #SPECIES
                 'Adelie' = 'cornflowerblue', 
                 'Chinstrap' = 'seagreen3',
                 'Gentoo' = 'maroon1')
```


```{r height_meters_hist, include=TRUE, fig.height=6.2}
(pen_mass_by_island_viz <- penguins %>% 
  ggplot(.) + 
  geom_histogram(aes(x=body_mass_g,
                 fill=island),
                 color='gray80') +  
  labs(x='\nBody mass (g)',
       y='Count') + 
  scale_x_continuous(labels = comma) + 
  scale_fill_manual(values = peng_cols) + 
  my.theme + 
  theme(legend.position = 'none'))
```

```{r fig.height=6.2, message=FALSE, warning=FALSE}
(pen_mass_by_island_viz <- pen_mass_by_island_viz + 
  plot_annotation(
    title = 'Distribution of penguin size on the Palmer Archipeligo in Antarctica',
    subtitle = glue('on {highlight_text("Biscoe", "cornflowerblue", "b")}, {highlight_text("Dream", "seagreen3", "b")}, and {highlight_text("Torgersen", "maroon1", "b")} islands'),
    caption='Tidy Tuesday Week 31 (2020)<br>Data source: palmerpenguins::',
    theme = theme_jk(markdown = TRUE,
                     plot_title_family = 'Gill Sans MT',
                     subtitle_family = 'Gill Sans MT',
                     caption_family = 'Gill Sans MT')))
```

```{r pen_mass_by_island_ridgeplot_viz, include=TRUE, fig.height=6.2}
(pen_mass_by_island_ridgeplot_viz <- penguins %>% 
  filter(complete.cases(.)) %>% 
  ggplot(.) + 
  ggridges::geom_density_ridges2(aes(x=body_mass_g,
                                    y=island,
                                    fill=island),
                                color='black')  + 
  labs(x='\nBody mass (g)',
       y='') + 
  scale_x_continuous(labels = comma) + 
  scale_fill_manual(values = peng_cols) + 
  my.theme + 
  theme(legend.position = 'none',
        axis.text.y = element_blank()))
```

```{r fig.height=7}
(pen_mass_by_island_ridgeplot_viz <- pen_mass_by_island_ridgeplot_viz + 
  plot_annotation(title = 'Distribution of the body mass of penguins on the Palmer Archipeligo',
                  subtitle = glue('on {highlight_text("Torgersen", "maroon1", "b")}, {highlight_text("Dream", "seagreen3", "b")}, {highlight_text("Briscoe", "cornflowerblue", "b")} islands'),
                  caption = 'Tidy Tuesday Week 31 (2020)<br>Data source: palmerpenguins::',
                  theme = theme_jk(markdown = TRUE,
                                   plot_title_family = 'Gill Sans MT',
                                   subtitle_family = 'Gill Sans MT',
                                   caption_family = 'Gill Sans MT')))
```

```{r flipper_bill_by_species_viz, include=TRUE, fig.height=6.2} 
(flipper_bill_by_species_viz <- penguins %>% 
  ggplot(.,
         aes(x=flipper_length_mm,
             y=bill_length_mm,
             color=species)) + 
  geom_smooth(method = 'lm', se = FALSE) + 
  geom_point() + 
  labs(x='\nFlipper length (mm)',
       y='Bill length (mm)\n') + 
  scale_color_manual(values = peng_cols) + 
  my.theme + 
  theme(legend.position = 'none'))
```

```{r fig.height=8, message=FALSE, warning=FALSE}
(flipper_bill_by_species_viz <- flipper_bill_by_species_viz + 
  plot_annotation(
    title = 'Relationship between **flipper length**, **bill length**, and **penguin species** on the Palmer Archipeligo in Antarctica',
    subtitle = glue('for {highlight_text("Adelie", "cornflowerblue", "b")}, {highlight_text("Chinstrap", "seagreen3", "b")}, and {highlight_text("Gentoo", "maroon1", "b")} penguins'),
    caption='Tidy Tuesday Week 31 (2020)<br>Data source: palmerpenguins::',
    theme = theme_jk(markdown = TRUE,
                     plot_title_family = 'Gill Sans MT',
                     subtitle_family = 'Gill Sans MT',
                     caption_family = 'Gill Sans MT')))
```

## Ternary diagram  

```{r scaling_vars, include=TRUE}
penguins %>% 
  mutate_if(is.numeric, scale) %>% 
  summarise_if(is.double, list(min, max), na.rm=TRUE)
```


```{r fig.height=8}
(penguin_ternary_viz <- penguins %>% 
  filter(complete.cases(.)) %>% 
  ggtern(aes(x = scale(bill_length_mm), 
               y = scale(body_mass_g), 
               z = scale(flipper_length_mm),
               color=species, fill=species)) + 
  geom_point(aes(fill=species), 
             shape = 21, 
             size = 3,
             alpha = .5) + 
  scale_color_manual(values = peng_cols) + 
  scale_fill_manual(values = peng_cols) + 
  labs(title = 'Relationship between bill length, body mass, and flipper length',
       subtitle = 'of penguin species on the Palmer archipeligo in Antarctica',
       x = '', y = '', z='') + 
  Larrowlab("Bill length (0-100 scaled)") + 
  Tarrowlab("Body mass (0-100 scaled)") + 
  Rarrowlab("Flipper length (0-100 scaled)") + 
  my.theme + 
  theme(plot.title = element_text(hjust=.9),
        plot.subtitle = element_text(hjust = -.53), 
        tern.axis.arrow.show = TRUE, 
        tern.axis.text = element_text(size = 14, colour = "grey20"),
        #tern.axis.title.T = element_text(),
        tern.axis.title.L = element_text(hjust = 0.2, vjust = 0.7, angle = -60),
        tern.axis.title.R = element_text(hjust = 0.8, vjust = 0.6, angle = 60),
        text = element_text(family = "Gill Sans MT", size = 18, color = "black"),
        legend.key = element_rect(fill = NA, color = NA),
        legend.key.size = unit(1, "cm")))
```

# Saving graphics  

```{r save_graphics, include=TRUE}
ggsave("graphics/pen_mass_by_island_viz.png", 
       pen_mass_by_island_viz,
       width = 12, height = 8, dpi = 300)

ggsave("graphics/pen_mass_by_island_ridgeplot_viz.png", 
       pen_mass_by_island_ridgeplot_viz,
       width = 10, height = 7, dpi = 300)

ggsave("graphics/flipper_bill_by_species_viz.png",
       flipper_bill_by_species_viz,
       width = 12, height = 8, dpi = 300)

ggsave("graphics/penguin_ternary_viz.png",
       penguin_ternary_viz,
       width = 12, height = 8, dpi = 300)
```
